### ISSUE TITLE
Driver not working when imported in Rancher

### ISSUE THREAD

**Issue by MiguelLucas** [packethost/docker-machine-driver-packet#73]
When creating a new node template based on the 0.6.0 release of this driver, it stays stuck after the authentication phase.

I only see this error appearing on the console when hitting "Next":
```
component.js:240 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'provisionable_on')
    at e.parsePlans (component.js:240:10)
    at component.js:82:37
    at v (rsvp.js:493:1)
    at b (rsvp.js:476:1)
    at invoke (backburner.js:340:1)
    at p.flush (backburner.js:229:1)
    at m.flush (backburner.js:426:1)
    at q._end (backburner.js:960:1)
    at _boundAutorunEnd (backburner.js:629:1)
```

**Comment by displague** [comment]
This report sounds more applicable to https://github.com/equinix/ui-driver-metal

**Comment by MiguelLucas** [comment]
Ok, will report it there

**Comment by displague** [comment]
Closing. Moved to https://github.com/equinix/ui-driver-metal/issues/42
